name = "cbse-g10"
main = "worker.js"
compatibility_date = "2024-01-01"

kv_namespaces = [
  { binding = "QBANK", id = "1bb275e528784864b8ab96ba72ffc15f" }
]

# KV namespace — create with: wrangler kv:namespace create "QBANK"
# Then paste the id here
# Optional: custom domain
# [routes]
# pattern = "api.yourdomain.com/*"
# zone_name = "yourdomain.com"
